### ISSUE TITLE
Add ability do disable weekly / monthly backup

### ISSUE THREAD

**Issue by akoievroman** [selim13/docker-automysqlbackup#19]
Hi,
WIll be great to have the ability to control these config values:
CONFIG_do_monthly
CONFIG_do_weekly

So that you can enable only weekly backups without monthly etc.

**Comment by selim13** [comment]
Hey!
Unfortunetly those config values are not available here as they come from a prerelease version of automysqlbackup 3 (which was a complete rewrite of automysqlbackup), while this image is based on latest release 2.5 (2.6 actually, as it comes with patches from debian).

I don't have plans moving to automysqlbackup 3 since it is completely abandoned.

**Comment by akoievroman** [comment]
Understood.
