### ISSUE TITLE
MySQL 8: caching_sha2_password not supported

### ISSUE THREAD

**Issue by brightdroid** [selim13/docker-automysqlbackup#6]
Using the container with mysql 8 I get following error:

> ERROR 2059 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded: Error loading shared library /usr/lib/mysql/plugin/caching_sha2_password.so: No such file or directory

**Comment by selim13** [comment]
Hey! Thanks for the report. 
Yes, looks like MySQL 8 have changed their default auth method to caching_sha2_password. The problem is that Alpine linux (which this image is based on) contains only MariaDB version of mysql-client and they are not planning to support sha2 any time soon.

So to fix this, I either need to manually compile mysql-client from mysql 8 or switch to debian as a base for this image.

For now you can work around this issue by either creating a separate backup user with an old auth method or altering auth method for the root user.
See this [stackoverflow thread](https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded)  for different solutions.

I will update the readme about current mysql 8 support status.

**Comment by brightdroid** [comment]
Ok, then I'll have to create my own docker image which support mysql 8. Thanks

**Comment by selim13** [comment]
I will leave this open, as I will eventually need to fix this.

**Comment by selim13** [comment]
Changed base image to debian:stretch-slim and now using official mysql-community-client-core package for mysqldump. This should solve problems with mysql 8 and hopefully won't introduce new ones.
